  protected function handleException(Exception $exception)
  {
    foreach ($this->exceptionCallbacks as $callback)
    {
      if (true === call_user_func($callback, $exception))
      {
        return;
      }
    }

    throw $exception;
  }

  /**
   * Asserts that the given argument is a callable.
   *
   * @param  mixed $callable
   * @throws InvalidArgumentException  If the argument is no callbale
   */
||||||||||||||||HAS_DOC_COMMENTNO_RETURN_TYPE
(PARAM_TYPENO_PARAM_DEFAULT)
(
    (AST_FOREACH
        (AST_PROP
            (AST_VAR))
        (AST_VAR)
        (NULL)
        (
            (AST_IF
                (AST_IF_ELEM
                    (AST_BINARY_OP
                        (AST_CONST)
                        (AST_CALL
                            (
                                (AST_VAR)
                                (AST_VAR))))
                    (
                        (AST_RETURN
                            (NULL)))))))
    (AST_THROW
        (AST_VAR)))||||||||